version: 2.1
jobs:
  install:
    docker:
      - image: node:14
    steps:
      - checkout
      - restore_cache:
            name: Restore Yarn dependencies cache
            keys:
              - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn dependencies cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

  lint:
    docker:
      - image: node:14
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Lint source code
          command: yarn lint

  test:
    docker:
      - image: node:14
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Test
          command: yarn test:coverage

workflows:
  test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
